name: Close inactive PRs
on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  close-prs:
    runs-on: self-hosted
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          stale-pr-label: "stale"
          stale-pr-message: "This PR is stale because it has been open for 30 days with no activity."
          close-pr-message: "This PR was closed because it has been inactive for 14 days since being marked as stale."
          days-before-pr-stale: 0
          days-before-pr-close: 1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
